# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitPTTcpp <- function(X, Xnew, Omega, k = 10L, rho0 = 0.2, rho0_mode = 0L, tran_mode = 1L, lognu_lowerbound = -1, lognu_upperbound = 4, n_grid = 5L, n_s = 5L, beta = 0, n_post_samples = 0L) {
    .Call('PTT_fitPTTcpp', PACKAGE = 'PTT', X, Xnew, Omega, k, rho0, rho0_mode, tran_mode, lognu_lowerbound, lognu_upperbound, n_grid, n_s, beta, n_post_samples)
}

